development:
  adapter: postgresql
  encoding: unicode
  database: crud_ar
  pool: 5
  username: gschool
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: crud_ar_test
  pool: 5
  username: gschool
  password: